ALTER TABLE `Order`
ADD COLUMN `trackingNumber` VARCHAR(100) NULL,
MODIFY COLUMN `status` ENUM('PENDING_CONFIRMATION', 'CONFIRMED', 'PROCESSING', 'READY_FOR_PICKUP', 'SHIPPED', 'COMPLETED', 'CANCELLED', 'EXPIRED') NOT NULL DEFAULT 'PENDING_CONFIRMATION';

ALTER TABLE `OrderEvent`
MODIFY COLUMN `status` ENUM('PENDING_CONFIRMATION', 'CONFIRMED', 'PROCESSING', 'READY_FOR_PICKUP', 'SHIPPED', 'COMPLETED', 'CANCELLED', 'EXPIRED') NOT NULL;
