ALTER TABLE `User`
  ADD COLUMN `provinceId` VARCHAR(2) NOT NULL DEFAULT '',
  ADD COLUMN `regencyId` VARCHAR(4) NOT NULL DEFAULT '',
  ADD COLUMN `districtId` VARCHAR(7) NOT NULL DEFAULT '',
  ADD COLUMN `villageId` VARCHAR(10) NOT NULL DEFAULT '',
  ADD COLUMN `postalCode` VARCHAR(5) NOT NULL DEFAULT '';
